### ISSUE TITLE
Cannot compile with go1.6

### ISSUE THREAD

**Issue by disktnk** [sbinet/go-hdf5#27]
```
$ go test
--- FAIL: TestCpxCmpd (0.01s)
	main_test.go:20: error: exit status 2
		:: data: [{0 0 1 [0 0 0] --0--} {1 1 0.5 [1 2 3] --1--} {2 4 0.3333333333333333 [2 4 6] --2--} {3 9 0.25 [3 6 9] --3--} {4 16 0.2 [4 8 12] --4--} {5 25 0.16666666666666666 [5 10 15] --5--} {6 36 0.14285714285714285 [6 12 18] --6--} {7 49 0.125 [7 14 21] --7--} {8 64 0.1111111111111111 [8 16 24] --8--} {9 81 0.1 [9 18 27] --9--}]
		:: file [SDScompound.h5] created (id=16777216)
		:: dset (id=83886080)
		:: dset.Write...
		panic: runtime error: cgo argument has Go pointer to Go pointer

		goroutine 1 [running]:
		panic(0x4105740, 0xc82000a3f0)
			/usr/local/go1.6.2/go/src/runtime/panic.go:481 +0x3e6
		github.com/sbinet/go-hdf5._cgoCheckPointer0(0x40d9260, 0xc82008a000, 0x0, 0x0, 0x0, 0x191)
			??:0 +0x4d
		github.com/sbinet/go-hdf5.(*Dataset).WriteSubset(0xc82000a3d8, 0x40cbca0, 0xc82008a000, 0x0, 0x0, 0x0, 0x0)
			/Users/tanakadaisuke/Development/Workspaces/Go/src/github.com/sbinet/go-hdf5/h5d.go:151 +0x1f8
		github.com/sbinet/go-hdf5.(*Dataset).Write(0xc82000a3d8, 0x40cbca0, 0xc82008a000, 0x0, 0x0)
			/Users/tanakadaisuke/Development/Workspaces/Go/src/github.com/sbinet/go-hdf5/h5d.go:158 +0x53
		main.main()
			/Users/tanakadaisuke/Development/Workspaces/Go/src/github.com/sbinet/go-hdf5/cmd/test-go-cpxcmpd/main.go:83 +0x8f5

FAIL
```

ref: https://golang.org/doc/go1.6#cgo

**Comment by disktnk** [comment]
I resolved by using `uintptr`, ref: https://github.com/disktnk/go-hdf5/blob/1b12b12b59ae834c19b7b4321f9922d565ad9076/h5d.go

If this workaround is acceptable, I'll send PR.

**Comment by disktnk** [comment]
sorry, this issue is duplicated with #25 , so close this issue.
